language: java
jdk:
  - oraclejdk8
before_install: cd TpAnual/
install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dcobertura.skip=true -B -V
script: mvn clean cobertura:check -B -V